### ISSUE TITLE
请求接口永远返回ok

### ISSUE THREAD

**Issue by changexbc** [mobejs/mobe#41]
设置接口返回err，但是请求接口永远返回ok，没有缓存，但是直接打开这个接口的链接却是返回err，请教原因

。。发现是通过cookie来储存接口的状态的，因为我是从localhost:8080请求localhost:3000。8080端口无法读到cookie所以一直返回ok的值，这种情况有什么解决办法吗

**Comment by nimojs** [comment]
感谢你的反馈，目前版本没有解决方法。但你看我增加如下功能你是否可以接受

-----

暂时先增加功能AJAX 提交的 GET POST 中带 _fms="ok" _fms="err" 来控制响应结果

```js
$.ajax({
   type: 'get',
   url: '/demo/'
   data: {
    _fms: "ok"
   }
})
```

---

以前是直接在 /fms/ 通过 AJAX 控制接口状态，后面因为fms可能要运行在线上供后端同事调试，为防止多人操作冲突就采取了浏览器 cookie 控制的方式。后续更新我思考下换一种“银弹”方案控制响应结果

目前我们的业务场景下不会出现问题是因为我们用 fms 模拟了后端页面渲染和AJAX响应所以没有遇到这个问题。我想知道你的8080是什么服务器，好在后续更新中支持这种情况

**Comment by changexbc** [comment]
@nimojs 谢谢作者耐心回复，8080是webpack-dev-server的端口。

**Comment by nimojs** [comment]
@changexbc 了解，webpack 的自动更新想要跟其他服务器结合有点麻烦。下次更新我会将 cookie 控制响应结果换成其他方式，无论从什么端口过来的请求都是在 /fms/ 中修改的结果
