### ISSUE TITLE
生成文档时，如何对生成的右侧导航（目录）进行修改。

### ISSUE THREAD

**Issue by x007xyz** [mobejs/mobe#44]
右侧导航是根据title生成的，我想将不同对象的增删改查使用文字分隔开，这样看起来更明显、更易识别，可不可以通过fms.doc()做到？

**Comment by nimojs** [comment]
目前做不到，只能在title 上下功夫，比如 

用户 - 添加用户
用户 - 删除用户

但后续的一个大版本会增加这个功能：
```
fms.doc('#用户')
fms.doc('## 账户操作')
```

最终会生成
```
用户
        账户操作
           添加用户 link
           删除用户 link
```

大版本的更新还会对增加很多功能，所以短期内不会发布。

**Comment by x007xyz** [comment]
好的，谢谢！期待下一个版本。
