### ISSUE TITLE
url地址中怎么加参数，就是在?后加参数

### ISSUE THREAD

**Issue by machao669** [mobejs/mobe#46]

**Comment by nimojs** [comment]
你是要根据不同 get 参数响应不同的结果么？

**Comment by nimojs** [comment]
可以看看新增的 fms.call api

https://github.com/mobejs/mobe/issues/19

---

后续大版本迭代会加入 match 解决相同 url 根据 get post header 不同返回不同内容的问题 
https://github.com/mobejs/mobejs.github.io/blob/gh-pages/api/ajax.md#match
