### ISSUE TITLE
指定err/ok总是返回ok?

### ISSUE THREAD

**Issue by zhlooking** [mobejs/mobe#47]
无论指定err或者ok，返回的都是ok内的JSON。求解？

**Comment by zhlooking** [comment]
fms是作为App的mock server使用的，在手机设备上访问server。可能是Cookies的问题么？谢谢。

**Comment by nimojs** [comment]
你需要在手机上访问 127.0.0.1:端口/fms/ 
然后在这个页面控制 ok err 

---

现在的方式是基于 cookie 控制。后续的一个大版本迭代会支持 cookie 控制和node变量控制（即在修改 ok err 后所有设备访问都是修改过的结果）

**Comment by zhlooking** [comment]
@nimojs 期待下一个版本添加支持，谢谢。
