### ISSUE TITLE
请问模版都支持哪几种像ejs支持吗?

### ISSUE THREAD

**Issue by FengZeming** [mobejs/mobe#48]
还有 在模版里怎么引入其它模版 ,譬如引入head模版

**Comment by nimojs** [comment]
任何编程语言任何模板都支持。只要按照 http://fmsjs.org/solution.html#封装解决方案 封装一个 渲染服务器就可以了

**Comment by FengZeming** [comment]
谢谢  ejs 这个实现了~ 看了 fms-handlebars-master  ~
