### ISSUE TITLE
怎样添加数据到session中？

### ISSUE THREAD

**Issue by huanggm** [mobejs/mobe#50]
后端使用smarty模版，模版中需要直接输出session中的用户名，那么怎样添加数据到session中呢？

万分感谢！！！

**Comment by nimojs** [comment]
以前考虑过这个问题。

smarty 直接获取 session 这是一个不好的方法。因为 session 的值应该属于业务逻辑代码控制的。而页面渲染的渲染数据应该是明确固定的。（所以FMS会根据配置的数据生成文档）

让后端明确在模板中将 session 值给到。

**Comment by huanggm** [comment]
确实，设置session不应该是FMS的事情，而是后端模版渲染接口的事情。
其实我的需求是直接在模版中输出session中某个变量值，如果不设置session，会直接报错。
比如 $smarty.session.username

所以我稍微修改了一下smarty渲染接口的实现，我在data属性中增加一个_SESSION属性，_SESSION是一个对象，最后在smarty渲染接口中将_SESSION对象中的数据设置到PHP的session中就行了

**Comment by nimojs** [comment]
这个 _SESSION 是 fms 传给 php 的还是在 php 的渲染代码中写死的？

**Comment by nimojs** [comment]
大概明白了，你是在渲染数据直接加了  
```
fms.view({
   data: {_SESSION:{"a":1}}
})
```
然后在php渲染服务器中取 data 中的 _SESSION 配置给PHP是吧

👍

**Comment by nimojs** [comment]
可以多关注 ：https://github.com/mobejs/mobejs.github.io 这个文档项目，要开发的新功能我都会在这里先记录。反复推敲后再实现。

---

你这种 `_SESSION` 的方式后续可以作为一种使用案例，用于体现基于渲染服务器如何扩展数据模拟。

**Comment by huanggm** [comment]
已关注，SESSION那块确实就是这么弄的
